### ISSUE TITLE
Feature: Add functionality for time-variable forcings.

### ISSUE THREAD

**Issue by ericbarefoot** [DeltaRCM/pyDeltaRCM#10]
One key feature that this model is missing right now is an easy way to allow the user to specify a vector for various quantities like discharge, sediment flux, or sea level. 

This way, we could also eliminate the `sea level = sea level + sea level rise` mechanism as it currently works in the code.

**Comment by amoodie** [comment]
I think that this *could* be done, but my preference would be to let it be something handled by subclassing, at least until we realize there is huge need for it.

This will be pretty simple to implement with subclassing, so I will add it as an example to the documentation for v2.0
