### ISSUE TITLE
capture error or trying to reopen netCDF file and raise new message?

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#100]
I'm not sure if this is really something for us to fix or for a user to be responsible for, but it got me stuck for like half an hour, so I'm gonna report it.

I was trying to use the checkpointing feature, bu kept getting this nondescript error message:
```bash
...
File "/home/mass/Dropbox/software/stratigraphy/pyDeltaRCM/pyDeltaRCM/init_tools.py", line 552, in load_checkpoint
    self.output_netcdf = Dataset(file_path, 'r+')
  File "netCDF4/_netCDF4.pyx", line 2358, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4/_netCDF4.pyx", line 1926, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'output/koala_6/pyDeltaRCM_output.nc'
```

Turns out, this issue can be raised for a number of netcdf related problems. Eventually I found that one of these issues is a corrupt file. Then it occurred to me, that I was connected to the same netcdf file in a different jupyter notebook with DeltaMetrics. After closing that notebook, checkpointing worked fine. 

It seems the netcdf folks and the xarray folks have had lots of similar issues raised in their repositories. I think xarray may have ended up capturing the error and raising something more helpful. I suggest we could do the same; pseudocode [for here](https://github.com/DeltaRCM/pyDeltaRCM/blob/2d5fd66dd07c952f323d682c2c2714af8b201434/pyDeltaRCM/init_tools.py#L513) below:

```python
# re-open the netCDF4 file
try:
    file_path = os.path.join(self.prefix, 'pyDeltaRCM_output.nc')
    self.output_netcdf = Dataset(file_path, 'r+', format='NETCDF4_CLASSIC')
except OSError as e:
    raise RuntimeError('Could not open the NetCDF file for checkpointing. This could be because the file is corrupt, or open in another interpreter. Be sure to close any connections to the file before proceeding.')
```

**Comment by elbeejay** [comment]
#182 adds the suggested try-except, but does not formally test that functionality.

A test should be designed that uses the `multiprocessor` to open a netCDF in one process, and then tries to resume a model using the same netCDF with another process - thus throwing the error that will be caught by the except.
