### ISSUE TITLE
Use Mixins for increased code readability?

### ISSUE THREAD

**Issue by ericbarefoot** [DeltaRCM/pyDeltaRCM#11]
Mixins are a way to break Python classes into multiple files. In our case, the goal is to break up `deltaRCM_tools.py` into several `.py` files grouped by functionality or something similar. The `Tools` class could then inherit methods from these other files, which would improve the readability somewhat, while retaining the object-oriented approach used here.

**Comment by elbeejay** [comment]
This is a good idea. `deltaRCM_tools.py` has some sections delimited by # marks so we could start with that (some are things like "randomization" and "water flow"). 

Not sure if the ultimate goal can or should be defined by a number of lines per file or a number of functions, but that could certainly help keep the files readable.

**Comment by ericbarefoot** [comment]
Agreed, the total amount of lines is probably not the best metric. I've started this, you can look on branch iss11 at [this commit](https://github.com/DeltaRCM/pyDeltaRCM_WMT/commit/9a1ce61f69b1f0046bc12d19e9823953d8eb944d) to see what I'm kinda thinking of.

**Comment by elbeejay** [comment]
Yes I think that makes sense to break water / sediment / initialization apart. Not sure if it makes sense to break out the random_walk functionality but that is an option as well.

**Comment by amoodie** [comment]
We may decide to revisit some of this in the future, but for now, let's close this.
