### ISSUE TITLE
Add functionality for HDF5 storage

### ISSUE THREAD

**Issue by ericbarefoot** [DeltaRCM/pyDeltaRCM#13]
When we start to think about running these models in parallel and over long periods of time, they will generate a lot of data. 

One way to easily deal with this data on disk is instead of writing separate files for different save states, we could write back and forth from an HDF5 file format. This is something I just learned about and am actively trying to figure out right now, but it seems like a promising way to aggregate and easily access all of the data generated by a model like this. 

In particular, I find it attractive to learn that this format works well with parallel computing, if for example, we want to try to run separate model instances in parallel to speed up computation.

**Comment by amoodie** [comment]
I think this has really proven not to be necessary for the pyDeltaRCM outputs, considering that we have achieved everything we needed to easily with netcdf, on the DeltaMetrics side, xarray works fine with both.
