### ISSUE TITLE
website materials and documentation

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#14]
Hi folks :wave: 

I spent some time last week procrastinating and avoiding doing my dissertation defense presentation (I passed!), and I made a website to house the DeltaRCM project. You can check out the site at [deltarcm.org](deltarcm.org). This is kind of a mockup right now, but I generally like the way it looks. If you have suggestions for changes to the site, or want to contribute contents (blog posts) let me know (or PR your changes). Do we like the logo?

![image](https://user-images.githubusercontent.com/8801322/78457293-cb72cd00-766e-11ea-9935-bfa8554656bf.png)

The site is set up to build the Jekyll contents at [https://github.com/DeltaRCM/deltarcm.org](https://github.com/DeltaRCM/deltarcm.org) and then deploys the built site to ~~AWS S3 for serving. I am using the AWS Cloudfront service to distribute the site because it provides an ssl connection. As a result, changes on S3 may not be reflected at deltarcm.org for approx 24 hours. However, you can always hit the S3 site directly at removed-link and see the non-cached Cloudfront version.~~ a `gh-pages` branch for hosting by Github pages. 

My vision is that for each of our "projects" we will have a site built at deltarcm.github.io/projectName, which will include the documentation and information for that specific project. I believe the easiest and most effective way for us to do this will be with the Sphinx package, allowing for a huge range of in-code documentation, tutorials, etc to be built and deployed (i.e., setting up for #2, #3, #4, #5, #6, #7). Sphinx is the package that all major open source projects use to build documentation (numpy, matplotlib, landlab), and I have recently gotten some experience building a site with it [https://amoodie.github.io/proffilo/index.html](https://amoodie.github.io/proffilo/index.html). I would like to set up these documentation frameworks for our projects, so that we can build out documentation as we develop the codes.

If you guys approve, I will go ahead and do the following:

- [x] set up the deltarcm.github.io website to redirect to deltarcm.org
- [x] add logos to the repositories of projects
- [x] set up documentation websites for each of the DeltaRCM projects I am aware of (pyDeltaRCM, DeltaMetrics) and integrate these websites with continuous integration builds to regularly build documentation, run code tests, and deploy to the websites. 
- [x] set up a `deltarcm-helper` github "machine account" to help with the automation [(see docs here)](https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users). I will share the account info with you guys, but we are unable to post it publicly anywhere.

Let me know what you think!

**Comment by elbeejay** [comment]
Sounds good. We should de-fork the delta-metrics as well so the repository in the deltarcm organization is the main one.

**Comment by ammilten** [comment]
All that sounds good to me. I like the look of the website, and there should be several other DeltaRCM-related projects out there that you can add. I think there's a vegetation module and also an ice module floating around. I'll be adding my own work to Github soon once everything has been written up and is close to being published.

**Comment by amoodie** [comment]
Okay, all the docs and website are setup up! You can hit em up at deltarcm.org
