### ISSUE TITLE
Matrix Preprocessor Bug With 1 Job

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#149]
The following configuration file throws an error (provided below). Relates to the way the ensemble is being handled, removing the line `ensemble: 1` from the configuration file solves the issue. 

YAML file:
```
out_dir: 'pardir'
verbose: 2
ensemble: 1
Length: 10.0
Width: 10.0
dx: 1.0
L0_meters: 1.0
N0_meters: 1.0
Np_water: 10
Np_sed: 10
parallel: 1
save_dt: 300
resume_checkpoint: False
save_checkpoint: True
save_eta_grids: True
```

Terminal output:
```
pyDeltaRCM --config par02.yaml --timesteps 10
Traceback (most recent call last):
  File "/home/jayh/anaconda3/envs/pydeltarcm/bin/pyDeltaRCM", line 11, in <module>
    load_entry_point('pyDeltaRCM', 'console_scripts', 'pyDeltaRCM')()
  File "/home/jayh/Documents/pyDeltaRCM/pyDeltaRCM/preprocessor.py", line 897, in preprocessor_wrapper
    pp = PreprocessorCLI()
  File "/home/jayh/Documents/pyDeltaRCM/pyDeltaRCM/preprocessor.py", line 761, in __init__
    self.construct_job_file_list()
  File "/home/jayh/Documents/pyDeltaRCM/pyDeltaRCM/preprocessor.py", line 299, in construct_job_file_list
    self.expand_yaml_matrix()  # creates self.file_list
  File "/home/jayh/Documents/pyDeltaRCM/pyDeltaRCM/preprocessor.py", line 206, in expand_yaml_matrix
    raise ValueError(
ValueError: Length of matrix key "seed" was 1, relocate to fixed configuration.

```

**Comment by amoodie** [comment]
I'm not sure this a bug exactly...[we raise this error here](https://github.com/DeltaRCM/pyDeltaRCM/blob/cecc34235d110109155d93cdcebf0da93c95998f/pyDeltaRCM/preprocessor.py#L204-L208). Running an ensemble of 1 is not an ensemble. An ensemble of 1 expands to a matrix of one:

```
matrix:
  seed:
    - 34324521
```

So the current implementation tells the user to reconfigure to remove the ensemble/matrix.

That said, I don't think there's any reason we _need_ to forbid an ensemble of 1...I think we just need to test that the infrastructure still works if the length is just one. Moreover, we could try and raise a better error message about it being from an ensemble, if that's what you mean to call a bug?

**Comment by elbeejay** [comment]
> Moreover, we could try and raise a better error message about it being from an ensemble, if that's what you mean to call a bug?

Yeah I guess that was more the point. "relocate to fixed configuration" wasn't super obvious to me. In the context of the ensemble I think it is a bit less clear because your yaml doesn't look like it has multiple configurations as it is "hidden" by the ensemble keyword.

**Comment by amoodie** [comment]
yeah I think that a better error is a good idea. :+1:
