### ISSUE TITLE
Should we de-fork?

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#15]
I think we should de-fork from `mperignon/pyDeltaRCM_WMT`, to make the project our own. 

The previous developers of DeltaRCM projects will continue to receive credit for their contributions in the code authors lists. 

Options we may be able to pursue: 

- start a brand new repository to develop from that is detatched from `mperignon/pyDeltaRCM_WMT` and then delete this fork. As far as I know, this will remove the authorship of the code base before the de-forking. 
- we can ask Mariela to "transfer ownership" of her repository to the DeltaRCM organization. Depending on her interest, we can make her an owner of DeltaRCM too. She can then fork the DeltaRCM code for her own repository. 
- I can look for more options. 

Let me know your thoughts.

**Comment by amoodie** [comment]
We de-forked on April 16, 2020.

**Comment by ericbarefoot** [comment]
Glad to see there's a paper trail
