### ISSUE TITLE
Do we need to keep the bmiDelta code and WMT code in this model repository?

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#16]
Does anyone have a good handle on how the BMI-Delta and WMT code stuff works? 

As best as I can tell, the [BmiDelta](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/master/pyDeltaRCM/bmi_delta.py#L12) is pretty much [just a wrapper](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/master/pyDeltaRCM/bmi_delta.py#L92) around the [pyDeltaRCM](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/master/pyDeltaRCM/deltaRCM_driver.py#L8) delta class, that redefines some input and output names.

I think that we should continue to support the basic model interface, but I'm wondering if we should split the wrapper out into another repository. We can have a respoitory `pyDeltaRCM` which is where we really do our development on the module (for those of us not using the BMI capabilities of the model) and then have another reposiotry that is `pyDeltaRCM_BMI` that uses `git submodules` to include the `pyDeltaRCM` code and wrap around it with the `BmiDelta` codes.

I think that this makes sense, because it decouples the actual pyDeltaRCM model from the BMI (whereas now, the codes are kind of confusingly mixed in the same repository). It will allow us to make all the changes we want to the internal working of pyDeltaRCM, and as long as we keep the public API of the model the same (i.e., `initialize`, `update`) then we can change the routines that get executed at will (and add optional support for new actions like, for example, `vegatation` or `arctic` during 

If we think this is something we want to explore more, we should get in touch with Mark Piper [https://github.com/mdpiper](https://github.com/mdpiper) and see what he thinks. I would not proceed with the separation if he thinks it is better to keep the two coupled.

**Comment by elbeejay** [comment]
I agree with the overall notion. My understanding is that CSDMS just moved to BMI 2.0 so this is a good time for us to decouple.

**Comment by amoodie** [comment]
@ericbarefoot if you are going to continue working on this, I think it would be a good time to overhaul how we configure models from a `.yml` too (as we discussed on #19). Additionally, I think it would make sense to have a "default" `.yml` file tucked away inside the package somewhere that we read from first, then override with any setttings that are selected inside the users `.yaml` file. 

I like this because it brings the startup cost of understanding for new users down to almost zero. Someone can `pip install` and the run really easily with `python -m pydelatrcm` or `python -m pydelatrcm --config myconfigfile.yml`. Or something like that.

**Comment by ericbarefoot** [comment]
>I think it would be a good time to overhaul how we configure models from a .yml too (as we discussed on #19).

Agreed, I'll work on this, and incorporate it into #19  when I reopen it.
