### ISSUE TITLE
record pyDeltaRCM version to log file when initializing / resume model run

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#189]
see title.

**Comment by elbeejay** [comment]
Thoughts on also recording the model *type*, something like `str(type(self))`? 

Might be useful to see if the model was the original DeltaModel or some sort of custom subclass from the log.

**Comment by amoodie** [comment]
yep makes sense to me. I think dumping that kind of information to the top of the log costs nothing could be invaluable.

Maybe some info on the OS too? Platform, version, python version? If verbosity is set pretty high, could even do a list of packages in environment? Not sure how readily available all of these are as strings...
