### ISSUE TITLE
fix handling of time-varying metadata when resuming from checkpoint

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#194]
I guess I don't know why this is not an issue for the grids which are also time-varying information stored in the netCDF, but this issue seems to only pertain to the time-varying metadata from what I can see. So maybe this has to do with how the metadata is re-created/re-initialized when resuming from a checkpoint...

But basically what seems to be happening is this: for a run starting from without checkpoint data, time-varying metadata is recorded properly. However if a checkpoint is resumed, the time-varying data becomes filled with what I assume are just the netCDF 'filler' values (`~9.9e36`). This can be seen in the below screenshot which is of a run that included resuming from a checkpoint. The first few 2 values for the time-varying metadata are correct, but the last 2 are clearly not.

The fix will need to sort out the root of the problem, but should also add checks on the metadata in the checkpointing tests to avoid similar problems in the future.

![image](https://user-images.githubusercontent.com/1770513/115970972-83d61200-a50b-11eb-9a87-4de698c0d11f.png)

**Comment by amoodie** [comment]
hm. weird. I had something similar, which I fixed in #151, but I guess it didn't catch this case. My runs with resuming checkpointing seem to be fine, but I think that may have been before #178, so maybe we broke something there?

Can you write a test to reproduce the bug? That's probably the "best programming practices" place to start...

**Comment by elbeejay** [comment]
> hm. weird. I had something similar, which I fixed in #151, but I guess it didn't catch this case. My runs with resuming checkpointing seem to be fine, but I think that may have been before #178, so maybe we broke something there?
> 
> Can you write a test to reproduce the bug? That's probably the "best programming practices" place to start...

Ya good idea, I'll write a test and probably start a draft PR to fix this as it is a pretty real issue

**Comment by elbeejay** [comment]
Added a series of checks to the integration test `test_checkpoint_nc` within `test_checkpointing.py` to include the metadata held in the netCDF, previously the test only checked the time and grids in the netCDF file. Once these checks are added, the test fails.

One can see this test fail in #195. I should be able to take a swing at actually implementing a fix sometime this weekend :crossed_fingers:
