### ISSUE TITLE
Raising a warning/error for unused YAML parameters

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#209]
From discussion generated in #206.

Andrew said:

> I think though it may make sense to treat these vars separately from the default vars then though (i.e., not merging the dicts). Instead, after importing the model variables, loop over any remaining variables. If the var is listed, but type is wrong, error. If the var is not listed, error. The cost of an extra for loop is nothing on run time.
> 
> So this would be in our `import_files`, below the import of values in the default dict:
> 
> ```python
> for k, v in user_dict.items():
>     if k in default_dict:
>         pass
>     else:
>         if k in self._subclass_parameters:
>             expected_type = v['type']
>             if type(user_dict[k]) in expected_type:
>                 input_file_vars[k] = user_dict[k]
>             else:
>                 raise TypeError('Input for "{_k}" not of the right type '
>                                 'in yaml configuration file "{_file}". '
>                                 'Input type was "{_wastype}", '
>                                 'but needs to be "{_exptype}".'
>                                 .format(_k=str(k), _file=self.input_file,
>                                         _wastype=type(k).__name__,
>                                         _exptype=expected_type))
>         else:
>             raise ValueError('error for var not declared in default or subclass')
> ```
> 
> There's probably some way to combine the verbose errors between the two for loops into a single f-string or something. I can figure that out.
> 
> I guess that the `self._subclass_parameters['custom_param']` could also go into `hook_import_files`, which would be more pythonic, but more verbose. Either way, I think you're right that having a default value and type checking it good.
> 
> This also has the benefit of spell checking -- I have mistyped `save_meta_grids` instead of `save_eta_grids` a few times...

Definitely worth considering as comments are ignored in yaml parsing so there is really no reason/excuse for someone to have YAML parameters that are not used in the model. Lines for specific subclasses could be commented out if needed for another model configuration... But the question of should a warning or error be raised is (almost) always a fair one.

**Comment by amoodie** [comment]
#252 added this warning for unused parameters
