### ISSUE TITLE
JOSS paper review minor issues

### ISSUE THREAD

**Issue by jhnienhuis** [DeltaRCM/pyDeltaRCM#215]
Hello @amoodie ,
First of all, apologies if I'm doing this review incorrectly or if i'm not following github customs. This is certainly a learning experience for me.

I noticed two smalls things when trying to follow your tutorial (https://deltarcm.org/pyDeltaRCM/guides/10min.html):
## 1) 

>>> import pyDeltaRCM
>>> default_delta = pyDeltaRCM.DeltaModel()
>>> for _ in range(0, 5):
>>>  delta.update()
>>> delta.finalize()

default_delta is changed to delta, so it will give an error message if you're blindly following these steps.

## 2) 

where can I find this file '10min_tutorial.yaml'?

Best wishes,
Jaap

**Comment by amoodie** [comment]
Hi Jaap,

You're a github pro as far as I can see! Thanks for pointing out these issues.

I've fixed the first error. For number 2), there is no file. Our intention is to have the user learn how to create the YAML file themselves, as knowing how to set up this file is pretty central to using the model. However, I see that wanting the user to make this file was obviously not clear in the documentation. I've updated the text in that section to hopefully make it clear that the user should make the file, and a brief description for how to make the file.

**Comment by kbarnhart** [comment]
openjournals/joss-reviews/issues/3398

**Comment by jhnienhuis** [comment]
Thanks @amoodie!, your answers make sense, although (from a end-user perspective) I usually run the default and adapt files where needed instead of trying to make new files myself. I see where you're coming from though.
Cheers,
Jaap

**Comment by amoodie** [comment]
For my own record keeping during revisions:

The issues identified in this review were addressed in #216.
