### ISSUE TITLE
Update to bmipy from basic_modeling_interface

### ISSUE THREAD

**Issue by ericbarefoot** [DeltaRCM/pyDeltaRCM#23]
`basic_modeling_interface` is the legacy package for BMI from CSDMS. We should update to the newer `bmipy`. #19 separates the wrapper, so this isn't urgent, but should be done before we deploy to the WMT. If we do split off the wrapper as in #16, then this issue should follow it.

**Comment by amoodie** [comment]
We updated to the latest version of `bmipy` in breaking off the BMI to [BMI_pyDeltaRCM](https://github.com/DeltaRCM/BMI_pyDeltaRCM).
