### ISSUE TITLE
Discharge in Metadata

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#232]
Am realizing we currently do not save any information about the inlet discharge in the metadata. Is this something that would be widely useful or should I just subclass myself a model that saves a time-series of water and sediment input discharge? 

Will be a small change but figured I'd give us a chance to discuss before implementing it.

**Comment by amoodie** [comment]
This information is kind of recorded as:
```python
Qw = meta.h0 * meta.u0 * meta.dx * meta.N0
Qs = Qw * (meta.C0_percent / 100)
```

though, I agree this is not as intuitive as directly recording it. I think each of these is set up to save as a time series too? Maybe excepting the inlet width and depth? and dx?

**Comment by elbeejay** [comment]
Yes it can definitely still be calculated using the existing metadata, it just feels like an unnecessary step to take.

> though, I agree this is not as intuitive as directly recording it. I think each of these is set up to save as a time series too? Maybe excepting the inlet width and depth? and dx?

We do have an mixture of static and time-varying metadata, and I wonder if we should standardize that. Two contrasting options come to mind:

1. Make all metadata time-varying at the expense of time/size of the output file (especially in the case of the `cell_type` array this could be costly)
2. Make all metadata static and when a user is implementing some kind of time variation, they should subclass the model to convert the relevant metadata field into a time-varying one.

Or we could always leave the mixture of metadata shapes as it is... feels like one of those design problems for which there is no singular solution that'll work for everything.

**Comment by amoodie** [comment]
> it just feels like an unnecessary step to take

I guess I see it as a tradeoff between completeness and clutter. 

I think Qw, at least might be commonly used enough that it would make sense to add directly into the file. Qs would then follow with C0_percent, so I don't know if that one really needs to be saved. Unless there's some obvious other way to decouple Qs from Qw I'm not thinking of...


> We do have an mixture of static and time-varying metadata, and I wonder if we should standardize that.

I mean, I love standards as much as everyone... I think the mixture is okay though. We have most of the boundary conditions saved as time-varying, which I think would cover most basic-user use cases. Once someone gets into subclassing, it kinda becomes swim at your own risk, I think --- you are responsible for making sure your model works and saves the necessary info once you stop messing with the model guts.

**Comment by elbeejay** [comment]
> I guess I see it as a tradeoff between completeness and clutter.
> 
> I think Qw, at least might be commonly used enough that it would make sense to add directly into the file. Qs would then follow with C0_percent, so I don't know if that one really needs to be saved. Unless there's some obvious other way to decouple Qs from Qw I'm not thinking of...

This is a great point - I can definitely see the addition of new metadata quickly becoming a "slippery slope." That being said I think we skip adding Qw and Qs to the metadata as they can be easily computed given the current metadata. Thanks for the insights! :+1:
