### ISSUE TITLE
Remove try-except from save_grids()

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#236]
Currently, [`save_grids()`](https://github.com/DeltaRCM/pyDeltaRCM/blob/99139d238e92b6e3a99ab220d16d2f3500942163/pyDeltaRCM/iteration_tools.py#L397) allows writing to the netCDF to fail without crashing the model via the use of a try-except statement.

This can be problematic as it:

- Will allow an unproductive model to continue using computational resources without recording data
- Allows a model with checkpointing to continue recording checkpoints *beyond* the time at which data is being or has been written to the netCDF

Barring some rational for keeping this in the code, I will implement a "bugfix" to remove this in a few weeks.

**Comment by amoodie** [comment]
sounds good to me, I can't think of any time someone would want to be recording to netcdf and then not care that recording stopped working.

To be clear, the "fix" here will be to change the behavior and raise an error to crash the run? Let's just try to make that error and log message as helpful as possible, e.g., recording the expected location of the file *and* whatever error information is raised from the netcdf library.

**Comment by elbeejay** [comment]
> To be clear, the "fix" here will be to change the behavior and raise an error to crash the run? Let's just try to make that error and log message as helpful as possible, e.g., recording the expected location of the file and whatever error information is raised from the netcdf library.

Yes aim would be to raise an error and force the run to stop. Good thoughts on the error/log message, will make them as informative as possible :+1:
