### ISSUE TITLE
math in docs is broken (same in DeltaMetrics) 

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#265]
See: https://deltarcm.org/pyDeltaRCM/info/hydrodynamics.html

I guess something sphinx related is broken here. The math is also broken on my local builds.

**Comment by elbeejay** [comment]
yeah I'm seeing this locally too, strange as the image assets for each equation are being generated and seem to be referenced properly in the html... will poke around
