### ISSUE TITLE
Topo diffusion before or after mud routing?

### ISSUE THREAD

**Issue by ericbarefoot** [DeltaRCM/pyDeltaRCM#30]
>With regards to the routing and order of diffusion, there doesn't seem to be any explanation for the change. Topographic diffusion used to be implemented after the routing of coarse particles al la the Matlab order of operations ([old commit](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blame/72fbc34716487c492af4d71384acea1d96316321/pyDeltaRCM/deltaRCM_tools.py#L898)). But after the `topo_diffusion` function was broken out separately, it just migrated to being called after all sediment routing had been performed.

_Originally posted by @elbeejay in https://github.com/DeltaRCM/pyDeltaRCM_WMT/pull/29#issuecomment-628872719_

[These lines](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/develop/pyDeltaRCM/sed_tools.py#L37-L40) are at issue. It is unclear when this change was introduced. What effect does it have? Investigation time!

**Comment by amoodie** [comment]
the change was made at:

https://github.com/DeltaRCM/pyDeltaRCM/commit/35b8063786c8a579bc3aca2229b71ae6af3c7c07#diff-078e631ec090a6fc9ae4d2648229f0d349fa2c8efed6384336197a0c7e05d5fd

It is not clear to me why it was moved from the end of inside the `self.sand_route` to after `self.mud_route` in the `sed_route` method.

**Comment by amoodie** [comment]
also note that it was stated in a comment in the old code:

```
#topo diffusion
#introduces lateral erosion as sed can be moved from banks
#into channels ##should be a function, for cleanliness
```

[link](https://github.com/DeltaRCM/pyDeltaRCM/commit/a8137feab62a2584b25c45ab990f764dd29e161e#diff-078e631ec090a6fc9ae4d2648229f0d349fa2c8efed6384336197a0c7e05d5fdL334-L336)

could this be the reason we have banks that aggrade in place, and prevent the channel from avulsion...
