### ISSUE TITLE
Documentation: Variables/Parameters

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#4]
List of the model variables and parameters with description, units, their default values, and how to access them in the code

**Comment by elbeejay** [comment]
Also need to fix the subsidence documentation so that it builds. 

Currently the `.. include:: subsidenceguide.rst` line in `userguide.rst` is not actually getting included in the final HTML build. Not sure why this is the case as it works locally for me, but will need to be sorted out at some point.

**Comment by amoodie** [comment]
> Also need to fix the subsidence documentation so that it builds.
> 
> Currently the .. include:: subsidenceguide.rst line in userguide.rst is not actually getting included in the final HTML build. Not sure why this is the case as it works locally for me, but will need to be sorted out at some point.

This was fixed with #110

**Comment by amoodie** [comment]
I think this is covered with the listing of all model attributes in the documentation [with YAML parameters here](https://deltarcm.org/pyDeltaRCM/info/yamlparameters.html), [default values here](https://deltarcm.org/pyDeltaRCM/reference/model/yaml_defaults.html) and [all model attributes here](https://deltarcm.org/pyDeltaRCM/_autosummary/pyDeltaRCM.model.DeltaModel.html#pyDeltaRCM.model.DeltaModel). 

Is there anywhere else we need this? Or anything else we need to cover? @elbeejay

**Comment by elbeejay** [comment]
> I think this is covered with the listing of all model attributes in the documentation [with YAML parameters here](https://deltarcm.org/pyDeltaRCM/info/yamlparameters.html), [default values here](https://deltarcm.org/pyDeltaRCM/reference/model/yaml_defaults.html) and [all model attributes here](https://deltarcm.org/pyDeltaRCM/_autosummary/pyDeltaRCM.model.DeltaModel.html#pyDeltaRCM.model.DeltaModel).
> 
> Is there anywhere else we need this? Or anything else we need to cover? @elbeejay

Good point, I think we've covered it all. I guess we've done a fair bit of documentation along the way after all.
