### ISSUE TITLE
update sphinx version

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#44]
We have a sphinx version issue.

I've pinned the sphinx version to 2.0.1 for now (in `requirements-docs.txt`), but I think when sphinx 3.1.x comes available, we should be able to add the `:recursive:` option to our `.. autosummary::` directives, and get the same behavior.

**Comment by elbeejay** [comment]
@amoodie just tried updating my local Sphinx version to the latest (v3.4.1) and I am not seeing the same issues we had previously with the autodocumentation (which if I remember right was missing API documentation of various functions/methods).

So I think we can probably go ahead and remove the fixed versioning of sphinx. I'm not sure what `:recursive:` adds to our documentation, the way the autosummary stuff is set up now continues to work as it has been.

**Comment by amoodie** [comment]
Yeah, I agree. I just updated my local to the same version and it seems fine :+1: 

Yeah, I guess just ignore that, I don't really remember what exactly I had in mind when I wrote that...
