### ISSUE TITLE
default number of water iterations too low

### ISSUE THREAD

**Issue by ericbarefoot** [DeltaRCM/pyDeltaRCM#48]
At the moment, the water iteration process (the number of times parcels are routed, then weights recalculated) only happens [one time](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/8f0e45d8e3a94391905869ce8b41e6244000d2d6/pyDeltaRCM/default.yml#L31-L33). 

We should have it go at least 5 times, since this allows the water surface and flux fields to more realistically simulate water flow. For example, see the following three plots of `eta` after 11 timesteps each. 

#### `itermax = 1`
![iter_1](https://user-images.githubusercontent.com/9613150/83582075-222d4380-a506-11ea-9177-e9a5fc3f9076.png)
#### `itermax = 2`
![iter_2](https://user-images.githubusercontent.com/9613150/83582077-22c5da00-a506-11ea-8aa6-5014183b4d70.png)
#### `itermax = 5`
![iter_5](https://user-images.githubusercontent.com/9613150/83582078-22c5da00-a506-11ea-8e7a-5c981b5d6242.png)

**Comment by amoodie** [comment]
can you confirm the behavior in the matlab version? I think you told me it was 5? If so, yeah I think change it!

**Comment by elbeejay** [comment]
I understand this being the case when the flow field is more of a 'jet' than a delta. After a distributary network is developed is this difference still apparent? I think we should probably test a few cases/longer scenarios to get a better idea of what impact the water iteration number has.

**Comment by ericbarefoot** [comment]
> I think we should probably test a few cases/longer scenarios to get a better idea of what impact the water iteration number has.

Yeah that's a good point @elbeejay. I suspect that the jet vs spread flow is probably more important initially, but I suspect (with no evidence atm) that the flow field evolves to some steady state solution with more iterations, so finding the optimum number would be important. 

> If so, yeah I think change it!

Lol. I believe in you. [I can confirm that it was 5 in Matlab originally](https://github.com/DeltaRCM/DeltaRCM/blob/1561c5c9e9911c22382560143e055216be31acb1/DeltaRCM_BASE.m#L15), where the hydro loop is done [here](https://github.com/DeltaRCM/DeltaRCM/blob/1561c5c9e9911c22382560143e055216be31acb1/DeltaRCM_BASE.m#L313). l certainly think this is perhaps the easiest issue to resolve, but we should be clear on the impacts, because it will definitely break [this test](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/develop/tests/test_consistent.py)

**Comment by amoodie** [comment]
# summary

With the help of our handy new preprocessor matrix expansion (#69), this was a really easy test to do. The yaml config at the end of the comment was used to do 500 timesteps runs (summarized below, and all results [attached as a zip](https://github.com/DeltaRCM/pyDeltaRCM_WMT/files/4957144/itermax_comparison.zip)).

I guess my overall interpretation is that @elbeejay is probably right. While `itermax` strongly influences the jet formation early on in the simulation, the effects later are much less obvious, if at all. Thoughts? Should we do a finer-`itermax`-interval set of experiments? Longer simulation?

# results
## eta

`itermax`  |  timestep 5 | timestep 350 | timestep 495
:------------:|:---------------:|:------------------:|:-----------------:
1  | ![eta_00005](https://user-images.githubusercontent.com/8801322/88117887-e3b91a00-cb81-11ea-80be-8628b6c0756e.png) | ![eta_00350](https://user-images.githubusercontent.com/8801322/88117913-f4699000-cb81-11ea-8f1a-27af0bb08502.png) | ![eta_00495](https://user-images.githubusercontent.com/8801322/88117936-00555200-cb82-11ea-9519-d506df1b5229.png)
2 | ![eta_00005](https://user-images.githubusercontent.com/8801322/88117982-17943f80-cb82-11ea-8983-5df94d547272.png) | ![eta_00350](https://user-images.githubusercontent.com/8801322/88118007-22e76b00-cb82-11ea-97a5-e143228cf828.png) | ![eta_00495](https://user-images.githubusercontent.com/8801322/88118010-2549c500-cb82-11ea-8c7b-f5565de51661.png)
5 | ![eta_00005](https://user-images.githubusercontent.com/8801322/88120330-49100980-cb88-11ea-839b-2078c8a21c53.png) | ![eta_00350](https://user-images.githubusercontent.com/8801322/88120337-4b726380-cb88-11ea-98c7-8412809036a5.png) | ![eta_00495](https://user-images.githubusercontent.com/8801322/88120339-4d3c2700-cb88-11ea-9d21-ab5d4005f4f3.png)

## velocity

`itermax`  |  timestep 5 | timestep 350 | timestep 495
:------------:|:---------------:|:------------------:|:-----------------:
1  | ![velocity_00005](https://user-images.githubusercontent.com/8801322/88120386-647b1480-cb88-11ea-8511-825245a60629.png) | ![velocity_00350](https://user-images.githubusercontent.com/8801322/88120389-66dd6e80-cb88-11ea-9e81-fec8143fab03.png) | ![velocity_00495](https://user-images.githubusercontent.com/8801322/88120393-69d85f00-cb88-11ea-9097-d82b4f7ec6c6.png)
2 | ![velocity_00005](https://user-images.githubusercontent.com/8801322/88120477-968c7680-cb88-11ea-8f55-b585a6d59f77.png) | ![velocity_00350](https://user-images.githubusercontent.com/8801322/88120480-9a1ffd80-cb88-11ea-88c6-5ee1866e82d5.png) | ![velocity_00495](https://user-images.githubusercontent.com/8801322/88120484-9d1aee00-cb88-11ea-878b-7411eebd61c5.png)
5 | ![velocity_00005](https://user-images.githubusercontent.com/8801322/88120501-aa37dd00-cb88-11ea-8368-9028d1412d3b.png) | ![velocity_00350](https://user-images.githubusercontent.com/8801322/88120506-ac9a3700-cb88-11ea-86bb-ec46749e266a.png) | ![velocity_00495](https://user-images.githubusercontent.com/8801322/88120507-ae63fa80-cb88-11ea-9521-195e8028841d.png)


## config
```yaml
out_dir: itermax_comparison
Length: 80.0
Width: 200.0
seed: 0
dx: 1.0
L0_meters: 3.0
S0: 0.0002
u0: 0.5
N0_meters: 5.0
h0: 1.0
H_SL: 0.0
f_bedload: 0.4
C0_percent: 0.1
toggle_subsidence: False
sigma_max: 0.0
save_eta_figs: True
save_discharge_figs: True
save_velocity_figs: True
save_dt: 5
save_strata: True
timesteps: 500

matrix:
  itermax:
    - 1
    - 2
    - 5
```

**Comment by elbeejay** [comment]
Thanks for spinning those up and looking into this @amoodie. My thought is that for the default value, we might want `itermax` to be set low so that the default configuration runs "faster".

**Comment by amoodie** [comment]
Yeah, I agree. To me, it seems like `itermax: 2` strikes a balance between "jet" and "radial symmetry" early on in the run, and since this seems to work to produce a good looking delta after 500 timesteps, I think it's probably a good default choice.
