### ISSUE TITLE
`omega_flow` is hardcoded to be 0.9 in `init_tools`

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#76]
`omega_flow` is hardcoded to be 0.9 in `init_tools` ([see here](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/9274692baa3535174d0fc01a599b02d576285c81/pyDeltaRCM/init_tools.py#L233)). 

This was never caught because [the test for setting this attribute](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/9274692baa3535174d0fc01a599b02d576285c81/tests/test_init_tools.py#L228) tests for the default value. 

So should `omega_flow` be a configurable parameter for the model or should it always be 0.9? Either way, this is an easy fix.

I'm guessing it should be configurable, and will submit a PR, but wanted to run it buy you folks first.

**Comment by amoodie** [comment]
@elbeejay @ericbarefoot any thoughts or preference on whether this should be configurable?

**Comment by elbeejay** [comment]
For posterity's sake, I'll just mention that the `omega_flow` parameter is the under-relaxation coefficient for the water flow. 

Since we are allowing pretty much every other parameter to be configurable, I don't see why this one would be an exception. Good catch ✋

**Comment by amoodie** [comment]
Right on. I agree. The same thing is actually the case with `Nsmooth` too, [where it is hardcoded to always be 1](https://github.com/DeltaRCM/pyDeltaRCM_WMT/blob/9274692baa3535174d0fc01a599b02d576285c81/pyDeltaRCM/init_tools.py#L182) regardless of the selection in the config yaml.

Changing this one though, is a breaking change to the consistency checks. This is breaking becuase we currently have the "default" set to be 5 in the `default.yml`, but it has been hardcoded to 1. So, should we change the default to 1, or update the consistency checks? 

I'd lean towards updating the consistency checks. Working on a pr for this stuff now btw.

**Comment by elbeejay** [comment]
I agree - updating the consistency checks is probably the way to go. If you're messing with the unit tests it might be a good time to move the timekeeping line too...
