### ISSUE TITLE
Conversion from Python 2.7 to Python 3.x

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#8]

**Comment by elbeejay** [comment]
Code is now functional in Python 3.x. Validation and code review ought to take place before we merge this branch into the master and accept it as the latest and greatest standard moving forward.

**Comment by amoodie** [comment]
@elbeejay can you update on this? We're all python3 no right?

**Comment by elbeejay** [comment]
Yeah, I had left it open for testing/bug checking but I suppose that will have to happen as we re-arrange and re-format the rest of the code base.
