### ISSUE TITLE
Additional / Longer Tests of "Checkpointing"

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#93]
Create additional / longer unit tests for the 'checkpointing' functionality (#74). In particular, ensure that the sparse matrix conversions into and out of `lilmatrix` for the stratigraphic information are working properly.

**Comment by elbeejay** [comment]
@amoodie can you think of any more tests we need to create for checkpointing? Since this issue was opened a bunch of integration tests have been created that checkpoint with/without a netCDF, test functionality with parallel features, etc. which I think covers "additional" tests. I'm not sure how necessary "longer" tests are, what do you think?

**Comment by amoodie** [comment]
Yeah, I agree that we have good coverage of checkpointing. I'm not sure if it was this issue or another, but I thought we discussed "longer" testing in the context of some kind of integration test that would ensure realistic behavior over long consistency-breaking runs. 

I think that may be a different issue though, or at least not directly related to checkpointing, so I think this can be closed :+1:
