### ISSUE TITLE
Add Finer Control For Subsiding Region

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#94]
Right now the user has control over the rate of subsidence and when the subsidence begins, but there is no easy way to control *where* the subsiding region is. The only way to do this currently is by modifying the model code directly. Default settings define a radial subsiding region, e.g.

![eta_00003](https://user-images.githubusercontent.com/1770513/91660779-58df0f80-ea9d-11ea-9cee-76dc04c58013.png)

Some potential ideas are:

1. Add radian boundaries as optional `.yml` parameters to define the size of the radial section that will be subsiding
2. Allow a set of points defining a closed boundary over which the subsidence occurs to be defined in the `.yml`

**Comment by amoodie** [comment]
Yeah I think it might be reasonable to add some basic options to the subsidence field (like defining radian boundaries), but we would never be able to cover all use cases. 

I think the current setup of the subsidence is to simply [compute `self.sigma` during initialization](https://github.com/DeltaRCM/pyDeltaRCM/blob/efa579b7637e6353a41cc3e3d6ae964f43287896/pyDeltaRCM/init_tools.py#L441), and then [add this field to the bed elevation each timestep](https://github.com/DeltaRCM/pyDeltaRCM/blob/efa579b7637e6353a41cc3e3d6ae964f43287896/pyDeltaRCM/deltaRCM_tools.py#L210). Therefore, all one needs to do is modify the field to suit their needs.

Enter model subclassing:
```
class CrazySubsidencePatternModel(pyDeltaRCM.DeltaModel):
    def __init__(self, input_file):
        super().__init__(input_file)

    def after_init(self):
        """Called at end of initialize."""
        self.sigma = np.random.random(size=(self.L, self.W))
```

Documentation with examples for subclassing (including custom subsidence fields) is ultimately a more flexible and maintainable approach to supporting options than implementing them all ourselves though the `.yml`.

and yes, I remember that `after_init` isn't really a needed hook, but it makes the point!

**Comment by elbeejay** [comment]
That's an excellent point and makes a good case for the `after_init` hook. 

Given the way subsidence is set up right now, we could probably add options for defining the radian boundaries fairly easily. And complex cases beyond that we could defer to the subclasses.
