### ISSUE TITLE
Add ability to save sediment discharge

### ISSUE THREAD

**Issue by elbeejay** [DeltaRCM/pyDeltaRCM#99]
We calculate sediment flux, `qs`, but we provide no options for saving this output.

We should add options to save the figures and grids for this variable.

**Comment by amoodie** [comment]
yep, I agree.

I think an overhaul of the netCDF file, in general, is needed.

For example, I think we should save boundary conditions, too. This relates to things we've discussed elsewhere (but I can't find at the moment).

Thanks for bringing this to the front with an issue. I'm going to tackle this soon.

**Comment by amoodie** [comment]
Here is an example of the structure we landed on in some old discussion on a slack thread. 

```
output.ext
|  elevation: 
|    | data: t-x-y array
|    | meta: t-value array, keys linking to main meta...
|  velocity: t-x-y array
|    | data: t-x-y array
|    | meta: t-value array, keys linking to main meta...
|  meta: a main metadata set, with some keys linking whatever, maybe containing grid coords?
```

I'll use this as a starting point for reworking the netcdf file.
